#!/usr/bin/env bash

# NixOS Configuration Structure Validation Script
# Validates directory structure compliance (Requirements 4.1, 4.2, 2.3)

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration root directory
CONFIG_ROOT="${1:-$(pwd)}"

# Validation results
ERRORS=0
WARNINGS=0

log_error() {
    echo -e "${RED}ERROR: $1${NC}" >&2
    ((ERRORS++))
}

log_warning() {
    echo -e "${YELLOW}WARNING: $1${NC}" >&2
    ((WARNINGS++))
}

log_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

log_info() {
    echo "INFO: $1"
}

# Validate required directory structure
validate_directory_structure() {
    log_info "Validating directory structure..."
    
    local required_dirs=(
        "hosts"
        "modules"
        "profiles" 
        "users"
        "lib"
        "scripts"
    )
    
    local required_module_dirs=(
        "modules/desktop"
        "modules/development"
        "modules/networking"
        "modules/security"
        "modules/services"
        "modules/system"
    )
    
    # Check top-level directories
    for dir in "${required_dirs[@]}"; do
        if [[ -d "$CONFIG_ROOT/$dir" ]]; then
            log_success "Directory $dir exists"
        else
            log_error "Required directory $dir is missing"
        fi
    done
    
    # Check module subdirectories
    for dir in "${required_module_dirs[@]}"; do
        if [[ -d "$CONFIG_ROOT/$dir" ]]; then
            log_success "Module directory $dir exists"
        else
            log_error "Required module directory $dir is missing"
        fi
    done
    
    # Check for required files
    local required_files=(
        "flake.nix"
        "lib/default.nix"
    )
    
    for file in "${required_files[@]}"; do
        if [[ -f "$CONFIG_ROOT/$file" ]]; then
            log_success "Required file $file exists"
        else
            log_error "Required file $file is missing"
        fi
    done
}

# Validate naming conventions
validate_naming_conventions() {
    log_info "Validating naming conventions..."
    
    # Check that all .nix files follow kebab-case or camelCase conventions
    while IFS= read -r -d '' file; do
        local basename=$(basename "$file" .nix)
        local dirname=$(dirname "$file")
        
        # Skip hardware-configuration.nix as it's generated by NixOS
        if [[ "$basename" == "hardware-configuration" ]]; then
            continue
        fi
        
        # Check for valid naming patterns
        if [[ "$basename" =~ ^[a-z][a-z0-9-]*[a-z0-9]$|^[a-z][a-zA-Z0-9]*$ ]] || [[ "$basename" == "default" ]]; then
            log_success "File $file follows naming convention"
        else
            log_warning "File $file may not follow naming convention (should be kebab-case or camelCase)"
        fi
        
        # Check that module files are in appropriate directories
        case "$dirname" in
            */modules/desktop*)
                if [[ ! "$basename" =~ (desktop|window|display|theme|hyprland|gnome|kde) ]]; then
                    log_warning "Module $file may be in wrong directory (desktop-related modules should be in modules/desktop/)"
                fi
                ;;
            */modules/development*)
                if [[ ! "$basename" =~ (dev|lang|tool|ide|git|editor) ]]; then
                    log_warning "Module $file may be in wrong directory (development-related modules should be in modules/development/)"
                fi
                ;;
            */modules/services*)
                if [[ ! "$basename" =~ (service|daemon|server|docker|ssh|web) ]]; then
                    log_warning "Module $file may be in wrong directory (service-related modules should be in modules/services/)"
                fi
                ;;
        esac
        
    done < <(find "$CONFIG_ROOT" -name "*.nix" -type f -print0)
}

# Validate module dependencies
validate_module_dependencies() {
    log_info "Validating module dependencies..."
    
    # Check that all imports in modules reference existing files
    while IFS= read -r -d '' file; do
        if [[ -f "$file" ]]; then
            # Extract import statements (simplified regex)
            local imports=$(grep -E "^\s*\./|^\s*\.\./|^\s*[a-zA-Z0-9/_-]+\.nix" "$file" 2>/dev/null || true)
            
            if [[ -n "$imports" ]]; then
                while IFS= read -r import_line; do
                    # Clean up the import line to extract just the path
                    local import_path=$(echo "$import_line" | sed -E 's/.*["\047]([^"'\'']*)["\047].*/\1/' | sed 's/;//')
                    
                    # Skip if it doesn't look like a file path
                    if [[ ! "$import_path" =~ \.(nix|toml|yaml|json)$ ]]; then
                        continue
                    fi
                    
                    # Resolve relative paths
                    local full_path
                    if [[ "$import_path" =~ ^\. ]]; then
                        full_path=$(realpath -m "$(dirname "$file")/$import_path" 2>/dev/null || echo "")
                    else
                        full_path="$CONFIG_ROOT/$import_path"
                    fi
                    
                    if [[ -n "$full_path" && -f "$full_path" ]]; then
                        log_success "Import $import_path in $file resolves correctly"
                    elif [[ -n "$import_path" ]]; then
                        log_error "Import $import_path in $file does not resolve to existing file"
                    fi
                done <<< "$imports"
            fi
        fi
    done < <(find "$CONFIG_ROOT" -name "*.nix" -type f -print0)
}

# Validate host configurations
validate_host_configurations() {
    log_info "Validating host configurations..."
    
    if [[ -d "$CONFIG_ROOT/hosts" ]]; then
        for host_dir in "$CONFIG_ROOT/hosts"/*; do
            if [[ -d "$host_dir" ]]; then
                local host_name=$(basename "$host_dir")
                log_info "Checking host: $host_name"
                
                # Check required host files
                local required_host_files=(
                    "configuration.nix"
                    "hardware.nix"
                    "users.nix"
                )
                
                for file in "${required_host_files[@]}"; do
                    if [[ -f "$host_dir/$file" ]]; then
                        log_success "Host $host_name has required file $file"
                    else
                        log_error "Host $host_name is missing required file $file"
                    fi
                done
            fi
        done
    else
        log_error "No hosts directory found"
    fi
}

# Validate user configurations
validate_user_configurations() {
    log_info "Validating user configurations..."
    
    if [[ -d "$CONFIG_ROOT/users" ]]; then
        # Check that templates directory exists
        if [[ -d "$CONFIG_ROOT/users/templates" ]]; then
            log_success "User templates directory exists"
        else
            log_warning "User templates directory is missing"
        fi
        
        # Check individual user directories
        for user_dir in "$CONFIG_ROOT/users"/*; do
            if [[ -d "$user_dir" && "$(basename "$user_dir")" != "templates" ]]; then
                local user_name=$(basename "$user_dir")
                log_info "Checking user: $user_name"
                
                # Check for user configuration files
                if [[ -f "$user_dir/default.nix" || -f "$user_dir/home.nix" ]]; then
                    log_success "User $user_name has configuration files"
                else
                    log_warning "User $user_name may be missing configuration files"
                fi
            fi
        done
    else
        log_error "No users directory found"
    fi
}

# Main validation function
main() {
    echo "=== NixOS Configuration Structure Validation ==="
    echo "Validating configuration at: $CONFIG_ROOT"
    echo ""
    
    validate_directory_structure
    echo ""
    validate_naming_conventions
    echo ""
    validate_module_dependencies
    echo ""
    validate_host_configurations
    echo ""
    validate_user_configurations
    echo ""
    
    echo "=== Validation Summary ==="
    if [[ $ERRORS -eq 0 && $WARNINGS -eq 0 ]]; then
        log_success "All validations passed!"
        exit 0
    elif [[ $ERRORS -eq 0 ]]; then
        echo -e "${YELLOW}Validation completed with $WARNINGS warnings${NC}"
        exit 0
    else
        echo -e "${RED}Validation failed with $ERRORS errors and $WARNINGS warnings${NC}"
        exit 1
    fi
}

# Run main function
main "$@"